# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:   ^/(_(profiler|wdt)|css|images|js)/
            security:  false
        main_login:
            pattern:        ^/login$
            anonymous:      true
        main:
            pattern:        ^/
            anonymous:      false
            provider:       in_memory
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     /login

    access_control:
        # require ROLE_ADMIN for /responsable
        - { path: ^/responsable, roles: ROLE_ADMIN }
        # require ROLE_USER for /hote
        - { path: ^/hote, roles: ROLE_USER}

#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}