<?php

namespace ZeCashDeskBundle\Repository;

/**
 * Cash_deskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cash_deskRepository extends \Doctrine\ORM\EntityRepository
{

    function afficherCodebarre(){

    }

}
