<?php

namespace ZeCashDeskBundle\Repository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $code
     * @return $this
     */
    public function genCode($code)
    {
        $this->createQueryBuilder('g')
            ->where("g.gencode > ?1")
            ->setParameter(1, $code)
            ->getQuery()
            ->getResult();

        return $this;
    }
}
