<?php

namespace ZeCashDeskBundle\Repository;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $query
     * @return $this
     */
    public function findByGencode($query)
    {
        return $this->createQueryBuilder('gen')
            ->where('gen.gencode = :gencode')
            ->setParameter('gencode', $query)
            ->getQuery()
            ->execute();
    }
}
